{% set name = "xlcompose" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xlcompose-{{ version }}.tar.gz
  sha256: 13238b9dbe6ffe22fb7f6eee87b2545fcae799e3686ebd9d8371e75e112d4141

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jinja2
    - pandas
    - python >=3.5
    - pyyaml
    - xlsxwriter >=1.1.8

test:
  imports:
    - xlcompose
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jbogaardt/xlcompose
  summary: A declarative API for composing spreadsheets from python
  license: MIT
  # License file manually packaged. See https://github.com/jbogaardt/xlcompose/pull/7
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
